-- Price data migration
TRUNCATE TABLE pp_prices;

INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '100ml', NULL, 50, 0.4472);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '100ml', NULL, 100, 0.4065);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '100ml', NULL, 1000, 0.3496);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '250ml', NULL, 50, 0.5772);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '250ml', NULL, 100, 0.5366);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '250ml', NULL, 1000, 0.4797);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '500ml', NULL, 50, 0.6422);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '500ml', NULL, 100, 0.5935);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '500ml', NULL, 1000, 0.5447);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '750ml', NULL, 50, 1.0488);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '750ml', NULL, 100, 1.0081);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '750ml', NULL, 1000, 0.9431);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '1000ml', NULL, 50, 1.1138);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '1000ml', NULL, 100, 1.0732);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '1000ml', NULL, 1000, 1.0163);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '2000ml', NULL, 50, 1.1788);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '2000ml', NULL, 100, 1.1382);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '2000ml', NULL, 1000, 1.0813);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '3000ml', NULL, 50, 1.9918);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '3000ml', NULL, 100, 1.9512);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '3000ml', NULL, 500, 1.9106);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '5000ml', NULL, 50, 2.5284);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '5000ml', NULL, 100, 2.2276);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '5000ml', NULL, 200, 2.2276);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft z okienkiem', '5000ml', NULL, 500, 2.0);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '100ml', NULL, 50, 0.5284);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '100ml', NULL, 100, 0.4878);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '100ml', NULL, 1000, 0.4309);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '250ml', NULL, 50, 0.5772);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '250ml', NULL, 100, 0.5366);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '250ml', NULL, 1000, 0.4797);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '500ml', NULL, 50, 0.6422);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '500ml', NULL, 100, 0.5935);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '500ml', NULL, 1000, 0.5447);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '750ml', NULL, 50, 1.0488);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '750ml', NULL, 100, 1.0081);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '750ml', NULL, 1000, 0.9431);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '1000ml', NULL, 50, 1.1138);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '1000ml', NULL, 100, 1.0732);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '1000ml', NULL, 1000, 1.0163);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '2000ml', NULL, 50, 1.1788);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '2000ml', NULL, 100, 1.1382);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '2000ml', NULL, 1000, 1.0813);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '3000ml', NULL, 50, 1.9918);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '3000ml', NULL, 100, 1.9512);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft z okienkiem', '3000ml', NULL, 500, 1.9106);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '100ml', NULL, 50, 0.496);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '100ml', NULL, 100, 0.4553);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '100ml', NULL, 1000, 0.3984);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '250ml', NULL, 50, 0.6586);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '250ml', NULL, 100, 0.6179);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '250ml', NULL, 1000, 0.561);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '500ml', NULL, 50, 0.756);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '500ml', NULL, 100, 0.7154);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '500ml', NULL, 1000, 0.6585);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '750ml', NULL, 50, 1.2358);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '750ml', NULL, 100, 1.1789);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '750ml', NULL, 1000, 1.122);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '1000ml', NULL, 50, 1.374);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '1000ml', NULL, 100, 1.3333);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '1000ml', NULL, 1000, 1.2764);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '2000ml', NULL, 50, 1.4716);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '2000ml', NULL, 100, 1.4309);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '2000ml', NULL, 1000, 1.374);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '3000ml', NULL, 50, 2.496);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '3000ml', NULL, 100, 2.4553);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft Aluminium', '3000ml', NULL, 500, 2.3984);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '100ml', NULL, 50, 0.6666);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '100ml', NULL, 100, 0.6098);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '100ml', NULL, 1000, 0.5772);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '250ml', NULL, 50, 0.748);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '250ml', NULL, 100, 0.6911);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '250ml', NULL, 1000, 0.6504);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '500ml', NULL, 50, 0.8618);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '500ml', NULL, 100, 0.813);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '500ml', NULL, 1000, 0.7407);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '750ml', NULL, 50, 1.2846);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '750ml', NULL, 100, 1.1789);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '750ml', NULL, 1000, 1.1057);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '1000ml', NULL, 50, 1.4308);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '1000ml', NULL, 100, 1.3008);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '1000ml', NULL, 1000, 1.2195);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '2000ml', NULL, 50, 1.5122);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '2000ml', NULL, 100, 1.3821);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '2000ml', NULL, 1000, 1.3008);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '3000ml', NULL, 50, 1.7886);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '3000ml', NULL, 100, 1.626);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Papier Kraft', '3000ml', NULL, 500, 1.5285);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '100ml', NULL, 50, 0.6666);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '100ml', NULL, 100, 0.6098);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '100ml', NULL, 1000, 0.5772);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '250ml', NULL, 50, 0.748);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '250ml', NULL, 100, 0.6911);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '250ml', NULL, 1000, 0.6504);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '500ml', NULL, 50, 0.8618);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '500ml', NULL, 100, 0.813);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '500ml', NULL, 1000, 0.7407);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '750ml', NULL, 50, 1.2846);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '750ml', NULL, 100, 1.1789);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '750ml', NULL, 1000, 1.1057);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '1000ml', NULL, 50, 1.4308);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '1000ml', NULL, 100, 1.3008);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '1000ml', NULL, 1000, 1.2195);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '2000ml', NULL, 50, 1.5122);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '2000ml', NULL, 100, 1.3821);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft', '2000ml', NULL, 1000, 1.3008);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '100ml', NULL, 50, 0.6666);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '100ml', NULL, 100, 0.6098);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '100ml', NULL, 1000, 0.5772);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '250ml', NULL, 50, 0.748);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '250ml', NULL, 100, 0.7561);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '250ml', NULL, 1000, 0.6504);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '500ml', NULL, 50, 0.8618);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '500ml', NULL, 100, 0.813);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '500ml', NULL, 1000, 0.7407);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '750ml', NULL, 50, 1.2846);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '750ml', NULL, 100, 1.1789);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '750ml', NULL, 1000, 1.1057);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '1000ml', NULL, 50, 1.4308);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '1000ml', NULL, 100, 1.3008);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '1000ml', NULL, 1000, 1.2195);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '2000ml', NULL, 50, 1.4716);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '2000ml', NULL, 100, 1.4309);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '2000ml', NULL, 1000, 1.374);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '3000ml', NULL, 50, 2.496);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '3000ml', NULL, 100, 2.4553);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biały Papier Kraft Aluminium', '3000ml', NULL, 500, 2.3984);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biodegradowalny Biały Papier Kraft', '250ml', NULL, 50, 1.5448);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biodegradowalny Biały Papier Kraft', '250ml', NULL, 100, 1.4634);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biodegradowalny Biały Papier Kraft', '250ml', NULL, 1000, 1.3821);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biodegradowalny Biały Papier Kraft', '500ml', NULL, 50, 1.7886);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biodegradowalny Biały Papier Kraft', '500ml', NULL, 100, 1.7073);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biodegradowalny Biały Papier Kraft', '500ml', NULL, 1000, 1.626);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biodegradowalny Biały Papier Kraft', '750ml', NULL, 50, 2.0326);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biodegradowalny Biały Papier Kraft', '750ml', NULL, 100, 1.9512);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Biodegradowalny Biały Papier Kraft', '750ml', NULL, 1000, 1.8699);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Kompostowalny Papier Kraft', '100ml', NULL, 50, 1.0406);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Kompostowalny Papier Kraft', '100ml', NULL, 100, 0.9512);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Kompostowalny Papier Kraft', '100ml', NULL, 1000, 0.8943);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Kompostowalny Papier Kraft', '250ml', NULL, 50, 1.1056);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Kompostowalny Papier Kraft', '250ml', NULL, 100, 1.0);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Kompostowalny Papier Kraft', '250ml', NULL, 1000, 0.9512);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Kompostowalny Papier Kraft', '500ml', NULL, 50, 1.2682);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Kompostowalny Papier Kraft', '500ml', NULL, 100, 1.1626);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Kompostowalny Papier Kraft', '500ml', NULL, 1000, 1.0976);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Kompostowalny Papier Kraft', '750ml', NULL, 50, 2.0326);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Kompostowalny Papier Kraft', '750ml', NULL, 100, 1.8537);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('overprint_product', 'Doypack Kompostowalny Papier Kraft', '750ml', NULL, 1000, 1.7561);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '100ml', NULL, 500, 3.9);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '100ml', NULL, 1000, 2.24);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '100ml', NULL, 5000, 1.4);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '100ml', NULL, 10000, 1.2);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '100ml', NULL, 15000, 1.06);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '100ml', NULL, 20000, 0.94);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '100ml', NULL, 50000, 0.64);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '100ml', NULL, 100000, 0.54);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '250ml', NULL, 500, 3.9);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '250ml', NULL, 1000, 2.45);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '250ml', NULL, 5000, 1.65);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '250ml', NULL, 10000, 1.41);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '250ml', NULL, 15000, 1.25);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '250ml', NULL, 20000, 1.13);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '250ml', NULL, 50000, 0.83);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '250ml', NULL, 100000, 0.73);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '500ml', NULL, 500, 3.9);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '500ml', NULL, 1000, 2.47);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '500ml', NULL, 5000, 1.73);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '500ml', NULL, 10000, 1.48);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '500ml', NULL, 15000, 1.36);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '500ml', NULL, 20000, 1.24);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '500ml', NULL, 50000, 0.94);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '500ml', NULL, 100000, 0.84);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '750ml', NULL, 500, 3.9);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '750ml', NULL, 1000, 2.69);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '750ml', NULL, 5000, 1.94);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '750ml', NULL, 10000, 1.7);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '750ml', NULL, 15000, 1.61);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '750ml', NULL, 20000, 1.55);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '750ml', NULL, 50000, 1.45);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '750ml', NULL, 100000, 1.35);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '1000ml', NULL, 500, 3.9);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '1000ml', NULL, 1000, 2.78);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '1000ml', NULL, 5000, 1.98);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '1000ml', NULL, 10000, 1.76);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '1000ml', NULL, 15000, 1.69);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '1000ml', NULL, 20000, 1.63);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '1000ml', NULL, 50000, 1.53);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '1000ml', NULL, 100000, 1.43);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '2000ml', NULL, 500, 3.93);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '2000ml', NULL, 1000, 3.01);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '2000ml', NULL, 5000, 2.14);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '2000ml', NULL, 10000, 1.91);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '2000ml', NULL, 15000, 1.81);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '2000ml', NULL, 20000, 1.76);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '2000ml', NULL, 50000, 1.66);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '2000ml', NULL, 100000, 1.56);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '3000ml', NULL, 500, 4.93);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '3000ml', NULL, 1000, 3.75);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '3000ml', NULL, 5000, 2.6);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '3000ml', NULL, 10000, 2.41);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '3000ml', NULL, 15000, 2.29);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '3000ml', NULL, 20000, 2.27);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '3000ml', NULL, 50000, 2.17);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/PE 70-100 - foliowy', '3000ml', NULL, 100000, 2.07);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '100ml', NULL, 500, 3.9);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '100ml', NULL, 1000, 2.45);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '100ml', NULL, 5000, 1.56);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '100ml', NULL, 10000, 1.36);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '100ml', NULL, 15000, 1.2);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '100ml', NULL, 20000, 1.07);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '100ml', NULL, 50000, 0.64);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '100ml', NULL, 100000, 0.54);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '250ml', NULL, 500, 3.9);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '250ml', NULL, 1000, 2.82);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '250ml', NULL, 5000, 1.92);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '250ml', NULL, 10000, 1.62);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '250ml', NULL, 15000, 1.47);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '250ml', NULL, 20000, 1.34);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '250ml', NULL, 50000, 0.83);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '250ml', NULL, 100000, 0.73);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '500ml', NULL, 500, 3.97);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '500ml', NULL, 1000, 2.85);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '500ml', NULL, 5000, 2.1);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '500ml', NULL, 10000, 1.81);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '500ml', NULL, 15000, 1.67);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '500ml', NULL, 20000, 1.61);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '500ml', NULL, 50000, 0.94);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '500ml', NULL, 100000, 0.84);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '750ml', NULL, 500, 4.4);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '750ml', NULL, 1000, 3.3);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '750ml', NULL, 5000, 2.44);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '750ml', NULL, 10000, 2.13);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '750ml', NULL, 15000, 2.02);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '750ml', NULL, 20000, 1.99);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '750ml', NULL, 50000, 1.45);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '750ml', NULL, 100000, 1.35);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '1000ml', NULL, 500, 4.49);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '1000ml', NULL, 1000, 3.62);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '1000ml', NULL, 5000, 2.56);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '1000ml', NULL, 10000, 2.36);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '1000ml', NULL, 15000, 2.22);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '1000ml', NULL, 20000, 2.16);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '1000ml', NULL, 50000, 1.53);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '1000ml', NULL, 100000, 1.43);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '2000ml', NULL, 500, 4.7);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '2000ml', NULL, 1000, 3.82);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '2000ml', NULL, 5000, 2.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '2000ml', NULL, 10000, 2.52);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '2000ml', NULL, 15000, 2.46);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '2000ml', NULL, 20000, 2.39);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '2000ml', NULL, 50000, 1.66);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '2000ml', NULL, 100000, 1.56);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '3000ml', NULL, 500, 6.41);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '3000ml', NULL, 1000, 5.11);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '3000ml', NULL, 5000, 3.51);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '3000ml', NULL, 10000, 3.3);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '3000ml', NULL, 15000, 3.19);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '3000ml', NULL, 20000, 3.08);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '3000ml', NULL, 50000, 2.17);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PET 12/ALU 7/PE 80-90 - foliowy z aluminium', '3000ml', NULL, 100000, 2.07);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET 12/PE 128 - foliowy', '5000ml', NULL, 500, 8.55);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET 12/PE 128 - foliowy', '5000ml', NULL, 1000, 7.33);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET 12/PE 128 - foliowy', '5000ml', NULL, 5000, 4.92);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET 12/PE 128 - foliowy', '5000ml', NULL, 10000, 3.92);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET 12/PE 128 - foliowy', '5000ml', NULL, 15000, 3.82);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET 12/PE 128 - foliowy', '5000ml', NULL, 20000, 3.72);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET 12/PE 128 - foliowy', '5000ml', NULL, 50000, 3.62);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET 12/PE 128 - foliowy', '5000ml', NULL, 100000, 3.52);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '100ml', NULL, 500, 4.2);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '100ml', NULL, 1000, 3.0);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '100ml', NULL, 5000, 2.1);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '100ml', NULL, 10000, 1.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '100ml', NULL, 15000, 1.65);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '100ml', NULL, 20000, 1.55);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '100ml', NULL, 50000, 1.35);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '100ml', NULL, 100000, 1.25);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '250ml', NULL, 500, 4.4);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '250ml', NULL, 1000, 3.2);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '250ml', NULL, 5000, 2.3);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '250ml', NULL, 10000, 2.0);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '250ml', NULL, 15000, 1.85);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '250ml', NULL, 20000, 1.75);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '250ml', NULL, 50000, 1.55);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '250ml', NULL, 100000, 1.45);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '500ml', NULL, 500, 4.6);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '500ml', NULL, 1000, 3.4);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '500ml', NULL, 5000, 2.5);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '500ml', NULL, 10000, 2.2);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '500ml', NULL, 15000, 2.05);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '500ml', NULL, 20000, 1.95);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '500ml', NULL, 50000, 1.75);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '500ml', NULL, 100000, 1.65);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '750ml', NULL, 500, 4.9);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '750ml', NULL, 1000, 3.7);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '750ml', NULL, 5000, 2.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '750ml', NULL, 10000, 2.5);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '750ml', NULL, 15000, 2.35);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '750ml', NULL, 20000, 2.25);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '750ml', NULL, 50000, 2.05);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '750ml', NULL, 100000, 1.95);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '1000ml', NULL, 500, 5.2);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '1000ml', NULL, 1000, 4.0);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '1000ml', NULL, 5000, 3.1);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '1000ml', NULL, 10000, 2.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '1000ml', NULL, 15000, 2.65);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '1000ml', NULL, 20000, 2.55);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '1000ml', NULL, 50000, 2.35);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '1000ml', NULL, 100000, 2.25);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '2000ml', NULL, 500, 5.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '2000ml', NULL, 1000, 4.6);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '2000ml', NULL, 5000, 3.7);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '2000ml', NULL, 10000, 3.4);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '2000ml', NULL, 15000, 3.25);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '2000ml', NULL, 20000, 3.15);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '2000ml', NULL, 50000, 2.95);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '2000ml', NULL, 100000, 2.85);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '3000ml', NULL, 500, 6.5);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '3000ml', NULL, 1000, 5.3);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '3000ml', NULL, 5000, 4.4);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '3000ml', NULL, 10000, 4.1);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '3000ml', NULL, 15000, 3.95);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '3000ml', NULL, 20000, 3.85);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '3000ml', NULL, 50000, 3.65);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP / AL7 / PE80 - papier z aluminium', '3000ml', NULL, 100000, 3.55);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '100ml', NULL, 500, 3.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '100ml', NULL, 1000, 2.6);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '100ml', NULL, 5000, 1.7);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '100ml', NULL, 10000, 1.4);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '100ml', NULL, 15000, 1.25);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '100ml', NULL, 20000, 1.15);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '100ml', NULL, 50000, 0.95);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '100ml', NULL, 100000, 0.85);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '250ml', NULL, 500, 4.0);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '250ml', NULL, 1000, 2.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '250ml', NULL, 5000, 1.9);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '250ml', NULL, 10000, 1.6);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '250ml', NULL, 15000, 1.45);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '250ml', NULL, 20000, 1.35);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '250ml', NULL, 50000, 1.15);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '250ml', NULL, 100000, 1.05);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '500ml', NULL, 500, 4.2);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '500ml', NULL, 1000, 3.0);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '500ml', NULL, 5000, 2.1);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '500ml', NULL, 10000, 1.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '500ml', NULL, 15000, 1.65);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '500ml', NULL, 20000, 1.55);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '500ml', NULL, 50000, 1.35);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '500ml', NULL, 100000, 1.25);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '750ml', NULL, 500, 4.5);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '750ml', NULL, 1000, 3.3);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '750ml', NULL, 5000, 2.4);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '750ml', NULL, 10000, 2.1);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '750ml', NULL, 15000, 1.95);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '750ml', NULL, 20000, 1.85);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '750ml', NULL, 50000, 1.65);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '750ml', NULL, 100000, 1.55);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '1000ml', NULL, 500, 4.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '1000ml', NULL, 1000, 3.6);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '1000ml', NULL, 5000, 2.7);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '1000ml', NULL, 10000, 2.4);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '1000ml', NULL, 15000, 2.25);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '1000ml', NULL, 20000, 2.15);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '1000ml', NULL, 50000, 1.95);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '1000ml', NULL, 100000, 1.85);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '2000ml', NULL, 500, 5.4);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '2000ml', NULL, 1000, 4.2);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '2000ml', NULL, 5000, 3.3);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '2000ml', NULL, 10000, 3.0);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '2000ml', NULL, 15000, 2.85);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '2000ml', NULL, 20000, 2.75);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '2000ml', NULL, 50000, 2.55);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '2000ml', NULL, 100000, 2.45);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '3000ml', NULL, 500, 6.1);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '3000ml', NULL, 1000, 4.9);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '3000ml', NULL, 5000, 4.0);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '3000ml', NULL, 10000, 3.7);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '3000ml', NULL, 15000, 3.55);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '3000ml', NULL, 20000, 3.45);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '3000ml', NULL, 50000, 3.25);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Doypack PAP /PET12 /CPP - papier z folią', '3000ml', NULL, 100000, 3.15);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '500ml', NULL, 500, 5.5);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '500ml', NULL, 1000, 4.3);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '500ml', NULL, 5000, 3.2);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '500ml', NULL, 10000, 2.9);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '500ml', NULL, 15000, 2.75);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '500ml', NULL, 20000, 2.65);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '500ml', NULL, 50000, 2.45);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '500ml', NULL, 100000, 2.35);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '1000ml', NULL, 500, 5.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '1000ml', NULL, 1000, 4.6);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '1000ml', NULL, 5000, 3.5);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '1000ml', NULL, 10000, 3.2);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '1000ml', NULL, 15000, 3.05);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '1000ml', NULL, 20000, 2.95);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '1000ml', NULL, 50000, 2.75);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '1000ml', NULL, 100000, 2.65);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '2000ml', NULL, 500, 6.4);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '2000ml', NULL, 1000, 5.2);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '2000ml', NULL, 5000, 4.1);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '2000ml', NULL, 10000, 3.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '2000ml', NULL, 15000, 3.65);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '2000ml', NULL, 20000, 3.55);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '2000ml', NULL, 50000, 3.35);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '2000ml', NULL, 100000, 3.25);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '3000ml', NULL, 500, 7.1);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '3000ml', NULL, 1000, 5.9);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '3000ml', NULL, 5000, 4.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '3000ml', NULL, 10000, 4.5);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '3000ml', NULL, 15000, 4.35);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '3000ml', NULL, 20000, 4.25);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '3000ml', NULL, 50000, 4.05);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '3000ml', NULL, 100000, 3.95);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '5000ml', NULL, 500, 8.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '5000ml', NULL, 1000, 7.6);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '5000ml', NULL, 5000, 5.5);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '5000ml', NULL, 10000, 4.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '5000ml', NULL, 15000, 4.65);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '5000ml', NULL, 20000, 4.55);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '5000ml', NULL, 50000, 4.35);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat Bottom PET/AL/PE  - aluminium + wentyl', '5000ml', NULL, 100000, 4.25);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '500ml', NULL, 500, 5.1);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '500ml', NULL, 1000, 3.9);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '500ml', NULL, 5000, 2.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '500ml', NULL, 10000, 2.5);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '500ml', NULL, 15000, 2.35);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '500ml', NULL, 20000, 2.25);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '500ml', NULL, 50000, 2.05);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '500ml', NULL, 100000, 1.95);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '1000ml', NULL, 500, 5.4);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '1000ml', NULL, 1000, 4.2);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '1000ml', NULL, 5000, 3.1);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '1000ml', NULL, 10000, 2.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '1000ml', NULL, 15000, 2.65);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '1000ml', NULL, 20000, 2.55);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '1000ml', NULL, 50000, 2.35);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '1000ml', NULL, 100000, 2.25);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '2000ml', NULL, 500, 6.0);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '2000ml', NULL, 1000, 4.8);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '2000ml', NULL, 5000, 3.7);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '2000ml', NULL, 10000, 3.4);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '2000ml', NULL, 15000, 3.25);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '2000ml', NULL, 20000, 3.15);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '2000ml', NULL, 50000, 2.95);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '2000ml', NULL, 100000, 2.85);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '3000ml', NULL, 500, 6.7);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '3000ml', NULL, 1000, 5.5);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '3000ml', NULL, 5000, 4.4);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '3000ml', NULL, 10000, 4.1);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '3000ml', NULL, 15000, 3.95);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '3000ml', NULL, 20000, 3.85);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '3000ml', NULL, 50000, 3.65);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '3000ml', NULL, 100000, 3.55);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '5000ml', NULL, 500, 8.4);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '5000ml', NULL, 1000, 7.2);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '5000ml', NULL, 5000, 5.1);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '5000ml', NULL, 10000, 4.4);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '5000ml', NULL, 15000, 4.25);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '5000ml', NULL, 20000, 4.15);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '5000ml', NULL, 50000, 3.95);
INSERT INTO pp_prices (type, material, size, print_type, qty_threshold, price) VALUES ('fullprint', 'Flat bottom PET/AL/PE Flat bottom - aluminium  (bez wentyla)', '5000ml', NULL, 100000, 3.85);